---
- name: Install redis
  ansible.builtin.package:
    name: "redis"
    state: present

- name: Start the Redis Service
  ansible.builtin.systemd:
    name: redis
    enabled: true
    state: started

- name: Wait for Redis service to be accessible
  ansible.builtin.wait_for:
    host: "localhost"
    port: 6379
    timeout: 300
