# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rop.spec

files_to_sync:
  - rop.spec

upstream_package_name: rop
downstream_package_name: rop

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      centos-stream-9:
        additional_repos:
          - copr://ekohl/obal
