# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foremanctl.spec

upstream_package_name: foremanctl
downstream_package_name: foremanctl

srpm_build_deps:
  - ansible-core

actions:
  create-archive:
    - bash -c 'ANSIBLE_COLLECTIONS_PATH=./build/collections/foremanctl ansible-galaxy install -r src/requirements.yml'
    - git archive --prefix foremanctl-0.0.1/ --output foremanctl.tar HEAD
    - tar --append --file foremanctl.tar --transform='s#^#foremanctl-0.0.1/#' build/collections/foremanctl
    - echo foremanctl.tar

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - epel-9
