# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foremanctl.spec

upstream_package_name: foremanctl
downstream_package_name: foremanctl

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - epel-9
