#!/bin/bash

python -m venv .venv
source .venv/bin/activate
pip install -e .
pip install -r requirements.txt # we should merge these 2 together
ansible-galaxy install -r requirements.yml

echo "Setup complete. Activate the virtualenv 'source .venv/bin/activate' and then run the cli 'rop'"
