---
pulp_image: quay.io/pulp/pulp-minimal:3.63
pulp_api_image: "{{ pulp_image }}"
pulp_content_image: "{{ pulp_image }}"
pulp_worker_image: "{{ pulp_image }}"

pulp_worker_count: 2

pulp_volumes:
  - /var/lib/pulp:/var/lib/pulp

pulp_api_container_name: pulp-api
pulp_content_container_name: pulp-content
pulp_worker_container_name: pulp-worker
