---
- name: Setup quadlet demo machine
  hosts:
    - localhost
  become: true
  vars:
    certificates_hostnames:
      - localhost
    certificates_ca_password: "CHANGEME"
    candlepin_db_password: "CHANGEME"
    candlepin_keystore_password: "CHANGEME"
    candlepin_oauth_secret: "CHANGEME"
    candlepin_ca_key: "/root/ssl-build/katello-default-ca.key"
    candlepin_ca_key_password: "/root/ssl-build/katello-default-ca.pwd"
    candlepin_ca_certificate: "/root/ssl-build/katello-default-ca.crt"
    candlepin_tomcat_key: "/root/ssl-build/localhost/localhost-tomcat.key"
    candlepin_tomcat_certificate: "/root/ssl-build/localhost/localhost-tomcat.crt"
    candlepin_client_key: "/root/ssl-build/{{ ansible_fqdn }}/{{ ansible_fqdn }}-foreman-client.key"
    candlepin_client_certificate: "/root/ssl-build/{{ ansible_fqdn }}/{{ ansible_fqdn }}-foreman-client.crt"
    foreman_ca_certificate: "/root/ssl-build/katello-default-ca.crt"
    foreman_client_key: "/root/ssl-build/{{ ansible_fqdn }}/{{ ansible_fqdn }}-foreman-client.key"
    foreman_client_certificate: "/root/ssl-build/{{ ansible_fqdn }}/{{ ansible_fqdn }}-foreman-client.crt"
    foreman_db_password: "CHANGEME"
    foreman_oauth_consumer_key: abcdefghijklmnopqrstuvwxyz123456
    foreman_oauth_consumer_secret: abcdefghijklmnopqrstuvwxyz123456
    httpd_server_ca_certificate: "/root/ssl-build/katello-server-ca.crt"
    httpd_client_ca_certificate: "/root/ssl-build/katello-default-ca.crt"
    httpd_server_certificate: "/root/ssl-build/{{ ansible_fqdn }}/{{ ansible_fqdn }}-apache.crt"
    httpd_server_key: "/root/ssl-build/{{ ansible_fqdn }}/{{ ansible_fqdn }}-apache.key"
    pulp_db_password: "CHANGEME"
    pulp_content_origin: "https://{{ ansible_fqdn }}"
    pulp_pulp_url: "https://{{ ansible_fqdn }}"
    postgresql_databases:
      - name: candlepin
        owner: candlepin
      - name: foreman
        owner: foreman
      - name: pulp
        owner: pulp
    postgresql_users:
      - name: candlepin
        password: "{{ candlepin_db_password }}"
      - name: foreman
        password: "{{ foreman_db_password }}"
      - name: pulp
        password: "{{ pulp_db_password }}"
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: ident }
      - { type: local, database: all, user: all, auth_method: ident }
      - { type: host, database: all, user: postgres, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: postgres, address: '0.0.0.0/0', auth_method: reject }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  roles:
    - geerlingguy.postgresql
    - redis
    - candlepin
    - httpd
    - pulp
    - foreman
