---
- name: Setup quadlet demo machine
  hosts:
    - localhost
  become: true
  vars_files:
    - "../vars/{{ certificate_source }}_certificates.yml"
    - "../vars/images.yml"
  vars:
    certificate_source: default
    certificates_hostnames:
      - "{{ ansible_fqdn }}"
      - localhost
    certificates_ca_password: "CHANGEME"
    candlepin_db_password: "CHANGEME"
    candlepin_keystore_password: "CHANGEME"
    candlepin_oauth_secret: "CHANGEME"
    candlepin_ca_key_password: "{{ ca_key_password }}"
    candlepin_ca_key: "{{ ca_key }}"
    candlepin_ca_certificate: "{{ ca_certificate }}"
    candlepin_tomcat_key: "{{ localhost_key }}"
    candlepin_tomcat_certificate: "{{ localhost_certificate }}"
    candlepin_client_key: "{{ client_key }}"
    candlepin_client_certificate: "{{ client_certificate }}"
    foreman_ca_certificate: "{{ ca_certificate }}"
    foreman_client_key: "{{ client_key }}"
    foreman_client_certificate: "{{ client_certificate }}"
    foreman_db_password: "CHANGEME"
    foreman_oauth_consumer_key: abcdefghijklmnopqrstuvwxyz123456
    foreman_oauth_consumer_secret: abcdefghijklmnopqrstuvwxyz123456
    httpd_server_ca_certificate: "{{ ca_certificate }}"
    httpd_client_ca_certificate: "{{ ca_certificate }}"
    httpd_server_certificate: "{{ server_certificate }}"
    httpd_server_key: "{{ server_key }}"
    pulp_db_password: "CHANGEME"
    pulp_content_origin: "https://{{ ansible_fqdn }}"
    postgresql_restarted_state: started
    pulp_pulp_url: "https://{{ ansible_fqdn }}"
    postgresql_restarted_state: started
    postgresql_databases:
      - name: candlepin
        owner: candlepin
      - name: foreman
        owner: foreman
      - name: pulp
        owner: pulp
    postgresql_users:
      - name: candlepin
        password: "{{ candlepin_db_password }}"
      - name: foreman
        password: "{{ foreman_db_password }}"
      - name: pulp
        password: "{{ pulp_db_password }}"
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: ident }
      - { type: local, database: all, user: all, auth_method: ident }
      - { type: host, database: all, user: postgres, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: postgres, address: '0.0.0.0/0', auth_method: reject }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  roles:
    - role: foreman_certs
      when: "certificate_source == 'installer'"
    - role: certificates
      when: "certificate_source == 'default'"
    - role: certificate_checks
      vars:
        certificate_checks_certificate: "{{ server_certificate }}"
        certificate_checks_key: "{{ server_key }}"
        certificate_checks_ca: "{{ ca_certificate }}"
    - geerlingguy.postgresql
    - redis
    - candlepin
    - httpd
    - pulp
    - foreman
    - role: theforeman.operations.installer
      vars:
        foreman_installer_scenario: katello
        foreman_installer_package: foreman-installer-katello
        foreman_installer_options:
          - '--foreman-proxy-oauth-consumer-key {{ foreman_oauth_consumer_key }}'
          - '--foreman-proxy-oauth-consumer-secret {{ foreman_oauth_consumer_secret }}'
          - '--tuning development'
      when: "certificate_source == 'installer'"
