---
- name: Setup basic stuff
  hosts: all
  become: true
  roles:
    - theforeman.forklift.etc_hosts

- name: Setup quadlet demo machine
  hosts:
    - quadlet
  become: true
  pre_tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - podman
          - python3-cryptography
          - python3-libsemanage
          - python3-requests
          - bash-completion
          - nmap
