---
name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'container-images/**'
      - '.github/workflows/container.yml'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'container-images/**'
      - '.github/workflows/container.yml'
      - 'docs/**'


concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          requirements_file: ../requirements.yml
          working_directory: src

  tests:
    strategy:
      fail-fast: false
      matrix:
        certificate_source:
          - default
          - installer
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup libvirt for Vagrant
        run: |
          sudo add-apt-repository --yes ppa:evgeni/vagrant
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends vagrant vagrant-libvirt libvirt-clients libvirt-daemon-system libvirt-daemon qemu-system-x86 qemu-utils dnsmasq
          sudo chmod 666 /var/run/libvirt/libvirt-sock
      - name: Install Ansible
        run: pip install --upgrade ansible-core
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install collection dependencies
        run: ansible-galaxy install -r requirements.yml
      - name: Start VMs
        run: |
          ./forge vms start
      - name: Create installer certificates
        if: contains(matrix.certificate_source, 'installer')
        run: |
          ./forge installer-certs
      - name: Run image pull
        run: |
          ./rop pull-images
      - name: Run deployment
        run: |
          ./rop deploy --certificate-source=${{ matrix.certificate_source }}
      - name: Run tests
        run: |
          ./forge test --pytest-args="--certificate-source=${{ matrix.certificate_source }}"
